name: Build and Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (leave empty for latest tag)"
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies and build the web UI
      - name: Install dependencies and build web UI
        working-directory: ./web-ui
        run: |
          bun install
          bun run build

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build the Rust project
      - name: Build Rust project
        run: cargo build --release

      # Compress the build artifacts
      - name: Compress build artifacts (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cp target/release/enoact .
          cp target/release/enoact-presence .
          tar -czvf enoact-linux-x86_64.tar.gz enoact enoact-presence

      - name: Compress build artifacts (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cp target\release\enoact.exe .
          cp target\release\enoact-presence.exe .
          7z a enoact-windows-x86_64.7z enoact.exe enoact-presence.exe

      - name: Create Release (Linux)
        uses: softprops/action-gh-release@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
            draft: true
            files: |
                ./enoact-linux-x86_64.tar.gz

      - name: Create Release (Windows)
        uses: softprops/action-gh-release@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
            draft: true
            files: |
                ./enoact-windows-x86_64.7z
